### ISSUE TITLE
Error after generating controller

### ISSUE THREAD

**Issue by Iruora** [strongloop/loopback-next#3049]
Hello, I have created a model, repository and controller using CLI, but after running the command `npm start` an error in the controller occurs in the method find(...).
**Argument of type 'Filter<AnyObject> | undefined' is not assignable to parameter of type 'Filter<Book> | undefined'.
  Type 'Filter<AnyObject>' is not assignable to type 'Filter<Book>'.**
I just fixed that issue by specifying the model class with the filter as follows :
```
async find(
    @param.query.object('filter', getFilterSchemaFor(Book))
    filter?: Filter<Book>,
  ): Promise<Book[]>
```

**Comment by dhmlau** [comment]
@Iruora , i believe we've fixed this issue in our latest release.  Could you please update `@loopback/cli` and install your app's dependencies again? Thanks.

**Comment by Kabangi** [comment]
Doesn't seem to help. 

I have updated to latest versions and still the issue persists.

This is how my dependencies look like.

```
 "dependencies": {
    "@bugsnag/js": "^6.1.0",
    "@loopback/authentication": "^1.0.16",
    "@loopback/boot": "^1.4.0",
    "@loopback/context": "^1.19.0",
    "@loopback/core": "^1.8.1",
    "@loopback/openapi-v3": "^1.6.1",
    "@loopback/repository": "^1.6.1",
    "@loopback/rest": "^1.15.0",
    "@loopback/rest-explorer": "^1.2.1",
    "@loopback/service-proxy": "^1.2.1",
    "@types/faker": "^4.1.5",
    "africastalking": "^0.4.0",
    "bcrypt": "^3.0.5",
    "jsonwebtoken": "^8.5.1",
    "loopback-connector-mysql": "^5.4.1",
    "loopback-connector-rest": "^3.4.1",
    "passport": "^0.4.0",
    "passport-http": "^0.3.0",
    "passport-http-bearer": "^1.0.1",
    "random-number-csprng": "^1.0.2"
  },
 "devDependencies": {
    "@loopback/build": "^1.7.1",
    "@loopback/testlab": "^1.5.0",
    "@loopback/tslint-config": "^2.1.0",
    "@types/node": "^10.14.8",
    "@types/passport": "^1.0.0",
    "@types/passport-http": "^0.3.8",
    "@types/passport-http-bearer": "^1.0.33",
    "faker": "^4.1.0",
    "tslint": "^5.17.0",
    "typescript": "^3.5.1"
  }
```

**Comment by aeremin** [comment]
@Iruora Thanks for filing this issue (and making it google-able)! Had no idea what's going on.

@Kabangi I think you need to update/install global dependency:
`npm i -g @loopback/cli@latest`
(which won't affect package.json).

Also, you would need to re-create your Controller (by `lb4 controller`, maybe deleting existing one is also needed). Basically, new CLI generates Controller's with more explicit type definitions which fixes the isu.

**Comment by dhmlau** [comment]
Besides deleting the existing controller, you can simply add the type param of `Where` and `Filter` as @Iruora suggested in the original description. 

Since we've fixed the original issue, docs and generated code (see PR https://github.com/strongloop/loopback-next/pull/3031/files), I'm closing this issue as resolved. Thanks!
