### ISSUE TITLE
Build making process is inconsistent.

### ISSUE THREAD

**Issue by mayank-SFIN571** [strongloop/loopback-next#3358]
While i am trying to run my test cases, the first time i try to make the build it is running fine. But the second time it is not building it.

To reproduce the bug, 

- Create a sample application.

- Write a test case.

- Run the test. 

- Run the test again. 

This is returning the error that outdir 'dist/\_\_test__' not found.

Following are the scripts to run the project.

```json
{
"scripts": {
    "build": "lb-tsc  --outDir dist",
    "build:watch": "lb-tsc --watch",
    "clean": "lb-clean dist",
    "lint": "npm run prettier:check && npm run eslint",
    "lint:fix": "npm run eslint:fix && npm run prettier:fix",
    "prettier:cli": "lb-prettier \"**/*.ts\" \"**/*.js\"",
    "prettier:check": "npm run prettier:cli -- -l",
    "prettier:fix": "npm run prettier:cli -- --write",
    "eslint": "lb-eslint --report-unused-disable-directives .",
    "eslint:fix": "npm run eslint -- --fix",
    "pretest": "npm run clean && npm run build",
    "test": "lb-mocha --allow-console-logs \"dist/__tests__\"",
    "posttest": "npm run lint",
    "test:dev": "lb-mocha --allow-console-logs dist/__tests__/**/*.js && npm run posttest",
    "prepublishOnly": "npm run clean && npm run build && npm run lint"
  },
"devDependencies": {
    "@loopback/boot": "^1.4.4",
    "@loopback/build": "^2.0.3",
    "@loopback/context": "^1.20.2",
    "@loopback/core": "^1.8.5",
    "@loopback/rest": "^1.16.3",
    "@loopback/testlab": "^1.6.3",
    "@loopback/tslint-config": "^2.1.0",
    "@types/express": "^4.17.0",
    "@types/lodash": "^4.14.135",
    "@types/node": "^10.14.8",
    "@types/passport": "^1.0.0",
    "@types/passport-google-oauth20": "^2.0.1",
    "@types/passport-http-bearer": "^1.0.33",
    "@types/passport-local": "^1.0.33",
    "@types/passport-oauth2-client-password": "^0.1.2",
    "lodash": "^4.17.11",
    "tslint": "^5.18.0",
    "typescript": "^3.5.2"
  }
}
```

**Comment by rohit-sourcefuse** [comment]
Following

**Comment by raymondfeng** [comment]
@SFIN571 Did you use `npm test` to run the test?

**Comment by SFIN571** [comment]
I am using npm run test

**Comment by samarpanB** [comment]
@raymondfeng , do we have any update on this issue ? I am also facing this problem.

**Comment by raymondfeng** [comment]
I cannot reproduce the problem with `@loopback/cli` 1.19.0. Here is what I tried:

```sh
lb4 t1
cd t1
npm test
// add a new test to `src/__tests__/acceptance/test.ts`
npm test
npm test
```

**Comment by samarpanB** [comment]
Yes. It doesn’t reproduce with 1.19. It only reproduces with version 2 onwards.

**Comment by raymondfeng** [comment]
We fixed the issue that tsc build cache was not removed during clean.

**Comment by samarpanB** [comment]
Okay. Which version shall we use ?

**Comment by samarpanB** [comment]
@raymondfeng Can you confirm if this issue is resolved with 2.0.4 version of @loopback/build ? This actually affect `npm run build` as well. So it hampers the development and build process. It just fails to create dist folder at times. Seems like a blocker for us.

**Comment by dougal83** [comment]
> @raymondfeng Can you confirm if this issue is resolved with 2.0.4 version of @loopback/build ? This actually affect `npm run build` as well. So it hampers the development and build process. It just fails to create dist folder at times. Seems like a blocker for us.

Can you try changing clean script in package.json to ``"clean": "lb-clean dist *.tsbuildinfo",`` ?  That might solve the build issue if you've not followed the changelogs on any pre-existing projects.  Just a hunch.

**Comment by raymondfeng** [comment]
As @dougal83 mentioned, the issue was in the code generation template for `package.json` after we enable `incremental` tsc build. It was fixed by https://github.com/strongloop/loopback-next/pull/3206.

Newly generated projects won't have the problem. If your existing project is broken, simply change clean script in `package.json` to `"clean": "lb-clean dist *.tsbuildinfo"`.

**Comment by mayank-SFIN571** [comment]
@raymondfeng I am still facing the issue.

Steps to reproduce
1. Run `lb4 app`.(configure it to be a basic app)
2. Run `npm run build`.
3. Delete the dist folder.
4. Run the `lb4 run build`.
This will not create a dist folder again.

All my dependencies including `@loopback/cli`, `@loopback/build` are up to date.

The versions are as follows:

@loopback/cli version: 1.20.0

@loopback/* dependencies:
  - @loopback/authentication: ^2.1.7
  - @loopback/boot: ^1.4.6
  - @loopback/build: ^2.0.5
  - @loopback/context: ^1.21.0
  - @loopback/core: ^1.8.7
  - @loopback/metadata: ^1.2.7
  - @loopback/openapi-spec-builder: ^1.2.7
  - @loopback/openapi-v3: ^1.9.0
  - @loopback/repository-json-schema: ^1.9.1
  - @loopback/repository: ^1.10.0
  - @loopback/rest: ^1.16.5
  - @loopback/testlab: ^1.7.1
  - @loopback/docs: ^1.27.0
  - @loopback/example-hello-world: ^1.2.7
  - @loopback/example-log-extension: ^1.2.7
  - @loopback/example-rpc-server: ^1.2.7
  - @loopback/example-todo: ^1.7.0
  - @loopback/example-soap-calculator: ^1.6.8
  - @loopback/service-proxy: ^1.2.7
  - @loopback/http-caching-proxy: ^1.1.7
  - @loopback/http-server: ^1.4.6
  - @loopback/example-todo-list: ^1.9.0
  - @loopback/dist-util: ^0.4.0
  - @loopback/rest-explorer: ^1.3.0
  - @loopback/eslint-config: ^2.0.2
  - @loopback/example-express-composition: ^1.5.0
  - @loopback/example-greeter-extension: ^1.3.7
  - @loopback/booter-lb3app: ^1.2.7
  - @loopback/example-lb3-application: ^1.1.7
  - @loopback/example-greeting-app: ^1.1.7
  - @loopback/example-context: ^1.2.7
  - @loopback/repository-tests: ^0.3.0

The `package.json` is the same which is made with CLI. Also i tiny details(if this effects anythig), I am using windows OS to develop.

**Comment by raymondfeng** [comment]
@mayank-SFIN571 Make sure you have something like the following in `tsconfig.json`:

```json
{
  "$schema": "http://json.schemastore.org/tsconfig",
  "extends": "@loopback/build/config/tsconfig.common.json",
  "compilerOptions": {
    "outDir": "dist",
    "rootDir": "src"
  },
  "include": ["src"]
}

```

**Comment by raymondfeng** [comment]
> Run lb4 app.(configure it to be a basic app)
Run npm run build.
Delete the dist folder.
Run the lb4 run build.
This will not create a dist folder again.

If you delete `dist` manually, please run `npm run clean` before `npm run build`.

You can run `npm run clean && npm run build` to have a clean build.

**Comment by mayank-SFIN571** [comment]
> > Run lb4 app.(configure it to be a basic app)
> > Run npm run build.
> > Delete the dist folder.
> > Run the lb4 run build.
> > This will not create a dist folder again.
> 
> If you delete `dist` manually, please run `npm run clean` before `npm run build`.
> 
> You can run `npm run clean && npm run build` to have a clean build.

@raymondfeng  This did the trick for me, thanks

**Comment by pankajcheema** [comment]
@raymondfeng your suggestion working fine

**Comment by nqcuongqt** [comment]
Delete file tsconfig.tsbuildinfo and dist folder and try to run command npm run build again.

**Comment by pankajcheema** [comment]
`npm run clean && npm run build`  is the best one .

**Comment by pankajcheema** [comment]
Hi ,

I am facing the issue again and this time `npm run clean && npm run build` concept not helping me

**Comment by pankajcheema** [comment]
you also need to remove tsbuildinfo also sometimes .
